apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-trigger-resetembeddingstatus
scopes:
  - lxi-ui-api
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 5m"